### PR TITLE
Fix incorrect file creation caused by not using null terminated strings

### PR DESCRIPTION
**Pull request by maurizi**

### CODE REVIEW

**Comment by maurizi** [comment]
@carllerche I had to update this since I first posted it.

**Comment by carllerche** [comment]
I looked to merge this, but this crate hadn't been updated for beta yet. I will try to get it done tomorrow. Sorry about the delay.

**Comment by carllerche** [comment]
I got the lib working on beta, but unfortunately, this PR uses unstable features :(

Another option would be to use the open function in nix: https://github.com/carllerche/nix-rust/blob/master/src/fcntl.rs#L74 which handles the null byte case.

**Comment by maurizi** [comment]
I took a look into using nix for this but couldn't quit figure out how to get everything working.

**Pull request closed without merging**
